version: "3"
services: 
  caddy:
    build: front
    environment: 
      TZ: "UTC"
      HOSTNAME: "localhost"
    ports:
      - 8000:80
      - 8001:443
    volumes:
      - ./front/Caddyfile:/code/Caddyfile
      - ./front/public:/public

  proxy:
    build: detox_proxy
    ports:
      - 5001:5001
