version: "3"
services: 
  caddy:
    build: front
    environment: 
      TZ: "UTC"
      HOSTNAME: "localhost"
    ports:
      - 80:80
      - 443:443

  proxy:
    build: detox_proxy
    ports:
      - 5001:5001
