version: "3"
services: 
  caddy:
    build: front
    environment: 
      TZ: "UTC"
      HOSTNAME: ${DETOX_PROXY_HOST}
    ports:
      - 80:80
      - 443:443

  proxy:
    build: detox_proxy
    ports:
      - 5001:5001
    depends_on:
      - api
    volumes:
      - ./detox_proxy/cert.pem:/code/cert.pem
      - ./detox_proxy/key.pem:/code/key.pem


  api:
    build: api
    env_file:
      - email.env
    links:
      - apidb
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pg_password"  # WARNING: 運用するときにはパスワードを変える・隠す
    depends_on:
      - apidb

  apidb:
    image: postgres
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pg_password"  # WARNING: 運用するときにはパスワードを変える・隠す
      DETOX_PROXY_HOST: ${DETOX_PROXY_HOST}
      DETOX_PROXY_PORT: ${DETOX_PROXY_PORT}
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata:
    driver: local  
