version: "3"
services: 
  caddy:
    build: front
    environment: 
      TZ: "UTC"
      HOSTNAME: "detoxproxy.com"
    ports:
      - 80:80
      - 443:443

  proxy:
    build: detox_proxy
    ports:
      - 5001:5001

  api:
    build: api
    env_file:
      - email.env
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pg_password"  # WARNING: 運用するときにはパスワードを変える・隠す

  apidb:
    image: postgres
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pg_password"  # WARNING: 運用するときにはパスワードを変える・隠す
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata:
    driver: local  
