version: "3"
services: 
  caddy:
    build: front
    environment: 
      TZ: "UTC"
      HOSTNAME: "localhost"
    ports:
      - 8000:80
      - 8001:443
    volumes:
      - ./front/Caddyfile:/code/Caddyfile
      - ./front/public:/public
      - ./detox_proxy/cert.crt:/cert/cert.crt
      - ./detox_proxy/cert.key:/cert/cert.key

  httpsproxy:
    build: detox_proxy
    ports:
      - 5001:5001
    depends_on:
      - api
    volumes:
      - ./detox_proxy/cert.crt:/code/cert.crt
      - ./detox_proxy/cert.key:/code/cert.key
    command: ./detox_proxy https

  httpproxy:
    build: detox_proxy
    ports:
      - 5000:5000
    depends_on:
      - api
    command: ./detox_proxy http


  api:
    build: 
      context: api
      dockerfile: DockerfileDev
    volumes:
      - ./api:/code
    env_file: 
      - email.env
    links:
      - apidb
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pg_password"  # WARNING: 運用するときにはパスワードを変える・隠す
      DETOX_PROXY_HOST: "localhost"
      DETOX_PROXY_PORT: "8001"
    depends_on:
      - apidb

  apidb:
    image: postgres
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pg_password"  # WARNING: 運用するときにはパスワードを変える・隠す
    volumes:
      - "pgdata:/var/lib/postgresql/data"


volumes:
  pgdata:
    driver: local 
